services:
  postgres:
    image: postgres:15.12
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=foobar
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=unit_test_demo
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3.9
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.9
    restart: always
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

volumes:
  postgres_data_container: